In [1]:
import pandas as pd
import numpy as np

In [2]:
import json
import csv

Data json was downlaoded from following webpage:
[Data Source](https://www.helcats-fp7.eu/catalogues/wp4_cat.html)

### Read data

In [3]:
# Opening JSON file
f = open('../Data/HCME_WP4_V01.json')

In [4]:
data = json.load(f)
f.close()

In [5]:
# len(data['columns'])

In [6]:
len(data['data'])

143

In [7]:
# data_csv = pd.DataFrame(columns=data['columns'])
# data_csv

In [8]:
# data['data'][0]

In [13]:
A = data['data'][0]
data_csv0 = pd.DataFrame(np.array(A).reshape(-1,len(A)), columns=data['columns'])
data_csv0

,HICAT_ID,SSE_LAUNCH [UTC],TARGET_NAME,TARGET_ARRIVAL [UTC],ICMECAT_ID,SC_INSITU,ICME_START_TIME [UTC],ARRIVAL_DIFFERENCE [hrs],SC_HELIODISTANCE [AU],SC_LONG_HEEQ [deg],...,MO_MVA_AXIS_LAT [deg],MO_MVA_RATIO,GSR_START_TIME [UTC],GSR_START_TIME [UTC],GSR_AXIS_LONG [deg],GSR_AXIS_LAT [deg],GSR_IMPACT [AU],VHTX [kms-1],VHTY [kms-1],VHTZ [kms-1]
0,HCME_A__20070521_01,2007-05-21 15:26,VENUS,2007-05-25 20:06,ICME_VEX_SGOOD_20070525_01,VEX,2007-05-25 03:35,16,0,-53,...,53,2,,,0,0,0,9999,9999,9999

In [14]:
# A = data['data'][1]
# data_csv1 = pd.DataFrame(np.array(A).reshape(-1,len(A)), columns=data['columns'])
# data_csv1

In [16]:

frames = []
for i in range(0, len(data['data'])):
    A = data['data'][i]
    # reshape the data and append it to frames 
    data_csv = pd.DataFrame(np.array(A).reshape(-1,len(A)), columns=data['columns'])
    frames.append(data_csv)

In [18]:
# concat the data 
result = pd.concat(frames)
result.head()

,HICAT_ID,SSE_LAUNCH [UTC],TARGET_NAME,TARGET_ARRIVAL [UTC],ICMECAT_ID,SC_INSITU,ICME_START_TIME [UTC],ARRIVAL_DIFFERENCE [hrs],SC_HELIODISTANCE [AU],SC_LONG_HEEQ [deg],...,MO_MVA_AXIS_LAT [deg],MO_MVA_RATIO,GSR_START_TIME [UTC],GSR_START_TIME [UTC],GSR_AXIS_LONG [deg],GSR_AXIS_LAT [deg],GSR_IMPACT [AU],VHTX [kms-1],VHTY [kms-1],VHTZ [kms-1]
0,HCME_A__20070521_01,2007-05-21 15:26,VENUS,2007-05-25 20:06,ICME_VEX_SGOOD_20070525_01,VEX,2007-05-25 03:35,16,0,-53,...,53,2,,,0,0,0,9999,9999,9999
0,HCME_A__20070521_01,2007-05-21 15:26,MESSENGER,2007-05-25 09:26,ICME_MES_SGOOD_20070524_01,MESSENGER,2007-05-24 22:45,10,0,-55,...,0,1,,,0,0,0,9999,9999,9999
0,HCME_B__20071009_01,2007-10-08 17:47,VENUS,2007-10-12 09:54,ICME_VEX_SGOOD_20071012_01,VEX,2007-10-12 17:24,-7,0,34,...,-18,4,,,0,0,0,9999,9999,9999
0,HCME_B__20071115_01,2007-11-14 22:08,VENUS,2007-11-17 18:18,ICME_VEX_SGOOD_20071117_01,VEX,2007-11-17 07:20,11,0,56,...,67,19,,,0,0,0,9999,9999,9999
0,HCME_B__20071204_01,2007-12-04 12:12,VENUS,2007-12-07 08:34,ICME_VEX_SGOOD_20071207_01,VEX,2007-12-07 18:08,-9,0,69,...,0,1,,,0,0,0,9999,9999,9999

In [21]:
result.describe().T

                         count unique                           top freq
HICAT_ID                   143    135           HCME_A__20070521_01    2
SSE_LAUNCH [UTC]           143    135              2007-05-21 15:26    2
TARGET_NAME                143      5                      EARTH_L1   68
TARGET_ARRIVAL [UTC]       143    143              2007-05-25 20:06    1
ICMECAT_ID                 143    126  ICME_MES_WINSLOW_20120311_01    2
SC_INSITU                  143      5                          Wind   68
ICME_START_TIME [UTC]      143    126              2012-03-11 06:31    2
ARRIVAL_DIFFERENCE [hrs]   143     45                            -9    9
SC_HELIODISTANCE [AU]      143      2                             0  106
SC_LONG_HEEQ [deg]         143     66                             0   68
SC_LAT_HEEQ [deg]          143     15                            -3   31
SOURCE_TYPE                143      3                             F   72
SOURCE_LONG_HEEQ [deg]     143     58                             0   67
SOURCE_LAT_HEEQ [deg]      143     41                             0   64
FLARE_CLASS                143     50                                 63
FLARE_START_TIME [UTC]     143     67                                 67
FLARE_END_TIME [UTC]       143     67                                 67
FLARE_PEAK_TIME [UTC]      143     67                                 67
CME_SSE_LONG_HEEQ [deg]    143     87                           -12    7
CME_SSE_LAT_HEEQ [deg]     143     48                             0    9
CME_SSE_SPEED [kms-1]      143    122                           370    3
CME_TARGET_SPEED [kms-1]   143    128                           539    3
MO_START_TIME [UTC]        143    126              2012-03-11 06:31    2
MO_END_TIME [UTC]          143    115              9999-99-99 99:99   15
MO_BMEAN [nT]              143     37                             8   17
MO_BSTD [nT]               143     14                             1   48
MO_BZMEAN [nT]             143     30                             0   19
MO_BZMIN [nT]              143     41                            -9   13
MO_MVA_AXIS_LONG [deg]     143     87                             0   34
MO_MVA_AXIS_LAT [deg]      143     76                             0   34
MO_MVA_RATIO               143     25                             2   21
GSR_START_TIME [UTC]       143     63                                 70
GSR_START_TIME [UTC]       143     63                                 70
GSR_AXIS_LONG [deg]        143     58                             0   70
GSR_AXIS_LAT [deg]         143     53                             0   70
GSR_IMPACT [AU]            143      1                             0  143
VHTX [kms-1]               143     71                          9999   45
VHTY [kms-1]               143     44                          9999   45
VHTZ [kms-1]               143     60                          9999   45

In [22]:
result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 143 entries, 0 to 0
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   HICAT_ID                  143 non-null    object
 1   SSE_LAUNCH [UTC]          143 non-null    object
 2   TARGET_NAME               143 non-null    object
 3   TARGET_ARRIVAL [UTC]      143 non-null    object
 4   ICMECAT_ID                143 non-null    object
 5   SC_INSITU                 143 non-null    object
 6   ICME_START_TIME [UTC]     143 non-null    object
 7   ARRIVAL_DIFFERENCE [hrs]  143 non-null    object
 8   SC_HELIODISTANCE [AU]     143 non-null    object
 9   SC_LONG_HEEQ [deg]        143 non-null    object
 10  SC_LAT_HEEQ [deg]         143 non-null    object
 11  SOURCE_TYPE               143 non-null    object
 12  SOURCE_LONG_HEEQ [deg]    143 non-null    object
 13  SOURCE_LAT_HEEQ [deg]     143 non-null    object
 14  FLARE_CLASS               143 non-null    object
 15  FLARE_START_TIME [UTC]    143 non-null    object
 16  FLARE_END_TIME [UTC]      143 non-null    object
 17  FLARE_PEAK_TIME [UTC]     143 non-null    object
 18  CME_SSE_LONG_HEEQ [deg]   143 non-null    object
 19  CME_SSE_LAT_HEEQ [deg]    143 non-null    object
 20  CME_SSE_SPEED [kms-1]     143 non-null    object
 21  CME_TARGET_SPEED [kms-1]  143 non-null    object
 22  MO_START_TIME [UTC]       143 non-null    object
 23  MO_END_TIME [UTC]         143 non-null    object
 24  MO_BMEAN [nT]             143 non-null    object
 25  MO_BSTD [nT]              143 non-null    object
 26  MO_BZMEAN [nT]            143 non-null    object
 27  MO_BZMIN [nT]             143 non-null    object
 28  MO_MVA_AXIS_LONG [deg]    143 non-null    object
 29  MO_MVA_AXIS_LAT [deg]     143 non-null    object
 30  MO_MVA_RATIO              143 non-null    object
 31  GSR_START_TIME [UTC]      143 non-null    object
 32  GSR_START_TIME [UTC]      143 non-null    object
 33  GSR_AXIS_LONG [deg]       143 non-null    object
 34  GSR_AXIS_LAT [deg]        143 non-null    object
 35  GSR_IMPACT [AU]           143 non-null    object
 36  VHTX [kms-1]              143 non-null    object
 37  VHTY [kms-1]              143 non-null    object
 38  VHTZ [kms-1]              143 non-null    object
dtypes: object(39)
memory usage: 44.7+ KB

In [23]:
# result.astype('object').dtypes

In [24]:
result.columns

Index(['HICAT_ID', 'SSE_LAUNCH [UTC]', 'TARGET_NAME', 'TARGET_ARRIVAL [UTC]',
       'ICMECAT_ID', 'SC_INSITU', 'ICME_START_TIME [UTC]',
       'ARRIVAL_DIFFERENCE [hrs]', 'SC_HELIODISTANCE [AU]',
       'SC_LONG_HEEQ [deg]', 'SC_LAT_HEEQ [deg]', 'SOURCE_TYPE',
       'SOURCE_LONG_HEEQ [deg]', 'SOURCE_LAT_HEEQ [deg]', 'FLARE_CLASS',
       'FLARE_START_TIME [UTC]', 'FLARE_END_TIME [UTC]',
       'FLARE_PEAK_TIME [UTC]', 'CME_SSE_LONG_HEEQ [deg]',
       'CME_SSE_LAT_HEEQ [deg]', 'CME_SSE_SPEED [kms-1]',
       'CME_TARGET_SPEED [kms-1]', 'MO_START_TIME [UTC]', 'MO_END_TIME [UTC]',
       'MO_BMEAN [nT]', 'MO_BSTD [nT]', 'MO_BZMEAN [nT]', 'MO_BZMIN [nT]',
       'MO_MVA_AXIS_LONG [deg]', 'MO_MVA_AXIS_LAT [deg]', 'MO_MVA_RATIO',
       'GSR_START_TIME [UTC]', 'GSR_START_TIME [UTC]', 'GSR_AXIS_LONG [deg]',
       'GSR_AXIS_LAT [deg]', 'GSR_IMPACT [AU]', 'VHTX [kms-1]', 'VHTY [kms-1]',
       'VHTZ [kms-1]'],
      dtype='object')

It is seen that whole data dtype are object.

In [25]:
result['ARRIVAL_DIFFERENCE [hrs]'].dtypes

dtype('O')

In [26]:

change_dtype_cols = ['ARRIVAL_DIFFERENCE [hrs]', 'SC_HELIODISTANCE [AU]',
       'SC_LONG_HEEQ [deg]', 'SC_LAT_HEEQ [deg]',
        'SOURCE_LONG_HEEQ [deg]', 'SOURCE_LAT_HEEQ [deg]',
        'CME_SSE_LONG_HEEQ [deg]',
       'CME_SSE_LAT_HEEQ [deg]', 'CME_SSE_SPEED [kms-1]',
       'CME_TARGET_SPEED [kms-1]', 
       'MO_BMEAN [nT]', 'MO_BSTD [nT]', 'MO_BZMEAN [nT]', 'MO_BZMIN [nT]',
       'MO_MVA_AXIS_LONG [deg]', 'MO_MVA_AXIS_LAT [deg]', 'MO_MVA_RATIO',
       'GSR_START_TIME [UTC]', 'GSR_START_TIME [UTC]', 'GSR_AXIS_LONG [deg]',
       'GSR_AXIS_LAT [deg]', 'GSR_IMPACT [AU]', 'VHTX [kms-1]', 'VHTY [kms-1]',
       'VHTZ [kms-1]']

In [27]:
# for col in change_dtype_cols:
#     col = str(col)
#     result.astype({col: 'float32'}).dtypes

In [28]:
# result.astype({'SC_HELIODISTANCE [AU]': 'float32'}).dtypes

In [29]:
file_path = "../Data/"
file_name = "Data_CME.csv"
result.to_csv(file_path+file_name)